SET NAMES UTF8;
DROP DATABASE IF EXISTS bitspaceman;
CREATE DATABASE bitspaceman CHARSET=UTF8;
USE bitspaceman;
CREATE TABLE user (id INT PRIMARY KEY AUTO_INCREMENT,uname VARCHAR(20),upwd VARCHAR(32));
INSERT INTO user VALUES(NULL,'ajin','12345');
INSERT INTO user VALUES(NULL,'花哥','12345');